Formula/viam-server.rb
did the following testing and this seems to work:
1. put the formula manually in the path
2. brew remove viam-server
3. brew install dannenserver (i'd renamed it)
4. start the service
5. see logs in the appropriate path
=> add log paths to our brew service

Formula/orb-grpc-server.rb
https://viam.atlassian.net/browse/DATA-605
A couple questions:
- After running `brew install`, I still had to manually link everything from `/opt/homebrew/Cellar/orb-grpc-server/HEAD-af2dec0/lib/` into `/usr/local/lib/`. Otherwise, I got a runtime error:
`dyld[13090]: Library not loaded: /tmp/orb-grpc-server-20221026-10229-f8sjnr/slam-libraries/viam-orb-slam3/ORB_SLAM3/Thirdparty/DBoW2/lib/libDBoW2.dylib
Referenced from: /opt/homebrew/Cellar/orb-grpc-server/HEAD-af2dec0/bin/orb_grpc_server
Reason: tried: '/tmp/orb-grpc-server-20221026-10229-f8sjnr/slam-libraries/viam-orb-slam3/ORB_SLAM3/Thirdparty/DBoW2/lib/libDBoW2.dylib' (no such file), '/usr/local/lib/libDBoW2.dylib' (no such file), '/usr/lib/libDBoW2.dylib' (no such file)`
I'm not sure if this is a problem with HEAD installs, or a …
=> [DATA-605] Orbslam homebrew formula

Formula/viam-server.rb
This uses https://github.com/viamrobotics/rdk/pull/1700 to include a tag version in brew based builds.
TODO: Bump to latest tag, after dependent PR merged in.
=> RSDK-778 - include tag version

.github/workflows/bump-versions.yml, Formula/aravis-cli.rb, Formula/carto-grpc-server.rb, Formula/intel-real-grpc-server.rb, Formula/orb-grpc-server.rb, Formula/tensorflowlite.rb, Formula/viam-server.rb, bump-version.sh
This should handle automatically bumping homebrew versions. To keep things simple, it just runs once an hour and polls for updates from the various repos (currently viam-server, carto-grpc-server, and orb-grpc-server) and looks for new versions. Zero integration should be needed on the other end.
The extra changes are because I ran "brew audit" against the formulae as well, so the changes actually in the formula themselves is just basically linting.
Lastly, as this is a completely public repo, with zero secrets or other integration and isn't needing even a custom docker image, I'm letting this run on a github runner.
=> [RSDK-804] Automatically bump homebrew versions

.github/workflows/bump-versions.yml, Formula/orb-grpc-server.rb, Formula/orb-slam3-module.rb
Ticket: https://viam.atlassian.net/browse/RSDK-2024
**Done:** Add the orb-slam3-module brew package
**Note:** The added file is identical to orb-grpc-server.rb except for two lines that I've highlighted.
**Tested on:** MacOS x86_64 (installed only since it does not function properly on macOS)
=> RSDK-2024 - Add an orbslam3 module brew package

Formula/cartographer-module.rb
Ticket: https://viam.atlassian.net/browse/RSDK-2860
Problem:
* `brew install cartographer-module` failed to build on an arm64 Mac.
Solution:
* I ran `brew remove --force $(brew list)` to uninstall all libraries
* I added missing dependencies until the brew package was installed successfully.
Tested on:
* Mac x86_64
=> RSDK-2860 - Fix cartographer missing dependencies

Formula/rplidar-module.rb
Ticket: https://viam.atlassian.net/browse/RSDK-2995
Problem:
* `brew install rplidar-module` failed to build on an x86_64 Mac.
Solution:
* I ran `brew remove --force $(brew list)` to uninstall all libraries
* I added missing dependencies until the brew package was installed successfully.
Tested on:
* Mac x86_64
=> RSDK-2995 - Add missing rplidar dependency (jpeg)

Formula/cartographer-module.rb
[Ticket](https://viam.atlassian.net/browse/RSDK-4147)
NOTE: This will be merged once cartographer-module `v0.3.20-rc0` is promoted to `stable`
=> [RSDK-4147] post-full-mod-update

.github/workflows/bump-versions.yml, Formula/viam-cli.rb, Formula/viam.rb
- add viam-cli to support `brew install viam`
- recent brew supports [tap+bottle](https://brew.sh/2020/11/18/homebrew-tap-with-bottles-uploaded-to-github-releases/). We should look into this so we can ship binaries to shrink download + speed up install for new users
=> RSDK-4706 add viam.rb formula for cli

.github/workflows/bump-versions.yml, Formula/viam.rb
- pin viam.rb to latest rdk commit to get auth fixes
- label this 0.8.1a
- remove viam.rb from bump-versions.yml temporarily
=> hotfix viam.rb 0.8.1a

Formula/viam-dialdbg.rb
`brew install viam-dialdbg` will `brew install rust` as a dependency. Adds a caveat to the brew formula that Rust may have been installed and users can either remove it or unlink it if they manage their Rust installations with something like `rustup`.
=> Add caveat about rust dependency for viam-dialdbg

Formula/ceres-solver@2.1.rb, Formula/suite-sparse@7.1.rb
- add pinned suite-parse 7.1.0
- consume it in our pinned ceres
- cartographer requests Ceres with SuiteParse component in its CMakeLists [here](https://github.com/cartographer-project/cartographer/blob/master/CMakeLists.txt#L39)
- before, I was unintentionally flagging off SuiteParse by removing a patch Ceres to do for version parsing
- current brew suite-sparse (7.3.0) changed an int to a long or something which breaks the build
=> add pinned suite-sparse, depend on pinned suite-sparse in ceres

Formula/cartographer-module.rb
This PR fixing the ongoing brew issue. The main issue was that Xcode was out of date (14 instead of 15.1) due to the reference being tied to Xcode which in turn required an OS update. 
The solution was to ensure that the environmental command lien tool path was linked to the independent install located at `/Library/Developer/CommandLineTools`. This can be confirmed on your system by running:
`xcode-select -p`
and updated with:
`xcode-select --switch /Library/Developer/CommandLineTools`
**JIRA Ticket:** https://viam.atlassian.net/browse/RSDK-6583
=> RSDK-6583 Fix brew install cartographer-module

.github/workflows/publish.yml, Formula/viam.rb
- pass root-url to `brew bottle` command (not just to `brew pr-upload`)
`bottle` affects download location, `pr-upload` affects upload, both are necessary, nothing is checking that they agree. previous version led to `brew install` attempting to download from homebrew/core on linux
=> use root-url in bottle command

.github/workflows/bottle.yml, .github/workflows/bump-versions.yml, needs-bump.sh
- needs-bump.sh outputs simple `true` / `false` when a bump is required
- trigger bottle.yml when needs-bump says to (only for `viam` formula for now i.e. the CLI)
So existing linux bottle doesn't get out of date with version bumps.
- bottle more architecures
- bottle more formulas
- error reporting
=> trigger bottle.yml script from bump-version

.github/workflows/bottle.yml, Formula/viam.rb
- refactor bottling to build each architecture in a job, but upload all architectures together
Before I was doing the full bottle process sequentially for each platform (linux, macos-14, etc). That broke because the brew commands require that you upload all platforms at once. This PR's change allows us to support multiple platforms.
I think homebrew's recommended flow for this is to open a PR, then run the pr-upload command against that PR.
I think PR is not an option because we're bumping automatically. Instead I've done:
- `brew install --bottle` + `brew bottle` in per-architecture jobs
- ^ that created a bottle.tar.gz and a bottle.json which get uploaded as artifacts
- after all per-arch jobs are done, the uploader job downloads all artifacts to the working directory
- runs `brew …
=> RSDK-5474 package CLI as bottle

Formula/viam-server.rb
- remove viam-server's tensorflowlite dependency
No longer needed and this is a long build.
I ran `brew remove tensorflowlite`, then `brew install viam-server`, and it succeeded.
=> remove viam-server dependency on tensorflowlite

.github/workflows/bottle.yml, .github/workflows/bump-versions.yml, Formula/viam-server.rb, Formula/viam.rb
- bottle viam-server (previously we were bottling only viam CLI)
- when bottling, install depends in a separate step from building the bottle. otherwise this tries to bottle nlopt and fails ([example](https://github.com/viamrobotics/homebrew-brews/actions/runs/11806813603/job/32892222602#step:4:189))
- in viam-server formula, bump node 18 -> 20 bc of deprecation warning. node is going away soon here anyway I think
Takes a while to build, tough first try / new laptop experience
- successful CI run https://github.com/viamrobotics/homebrew-brews/actions/runs/11807743220
=> bottle viam-server

.github/workflows/bottle.yml, Formula/viam-server.rb, Formula/viam.rb
- preinstall pkg-config at the top of bottling
Otherwise, viam-server build fails (but only in runners, where there's a random conflicting pkg-config installation)
=> fix viam-server build

Formula/viam-cpp-sdk.rb
Following the error message posted in the ticket:
> CMake Error at /opt/homebrew/Library/Homebrew/cmake/trap_fetchcontent_provider.cmake:12 (message):
>   Refusing to populate dependency 'xtl' with FetchContent while building in
>   Homebrew, please use a formula dependency or add a resource to the formula.
Homebrew used to pass `FETCHCONTENT_FULLY_DISCONNECTED=ON` to CMake, which made it so that FetchContent would never actually pull anything from online. However we were using the signature of FetchContent with [`find_package` integration](https://cmake.org/cmake/help/latest/module/FetchContent.html#integrating-with-find-package) so this was able to handle the homebrew case transparently, because it was just calling `find_package` and using the version in our brew formula. However …
=> RSDK-8395: Workaround homebrew change that broke recipe

.github/workflows/bump-versions.yml, Formula/viam-cpp-sdk.rb, Formula/viam-server.rb, Formula/viam.rb, bump-version.sh, fake-tap.sh
- pin to last week's brew image + disable auto-update
- refactor brew setup step in yml to `fake-tap.sh` so people can run locally for debugging
- (incidental) the autobump ran in this branch
It seems like the `--write-only` flag in the bump PR changed or broke and our stuff stopped working
=> pin brew container to fix builds

Formula/viam-server.rb
- move nlopt-static to a `:build` dep in viam-server formula
Currently users have to build nlopt-static even when downloading a bottle. This is 1) redundant, but 2) increases the odds that something goes wrong; without nlopt-static, nothing gets compiled in bottle mode I believe. An in-house user today ran into trouble today that would have been avoided if nlopt-static were omitted.
I made this change on my local tap and verified that nlopt wasn't built.
Some or all of the other libraries are also not runtime deps (but at least don't require a build, as otterverse points out).
=> make nlopt-static a build-time dep
